name: CI / SonarCloud
on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    env:
      SONAR_PR_BRANCH: ${{github.head_ref}}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build & Run Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{secrets.PROJECT_KEY}}
          SONAR_ORG_KEY: ${{secrets.ORG_KEY}}
          SONAR_PULL_REQUEST_KEY: ${{github.event.pull_request.number}}
          SONAR_PULL_REQUEST_BASE: ${{github.base_ref}}
        run: |
          mvn -B -DskipTests verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.organization=$SONAR_ORG_KEY \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.pullrequest.key=$SONAR_PULL_REQUEST_KEY \
            -Dsonar.pullrequest.branch=$SONAR_PR_BRANCH \
            -Dsonar.pullrequest.base=$SONAR_PULL_REQUEST_BASE